[package]
name = "kutrace-usdt-fixture"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "kutrace-usdt-fixture"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
cc.workspace = true
